(() => {
  const views=[...document.querySelectorAll('.view')], nav=[...document.querySelectorAll('.nav-item')], title=document.getElementById('viewTitle');
  const titles={overview:'Обзор',users:'Пользователи',subscriptions:'Подписки',ai:'AI',market:'Market Pulse',system:'Система'};
  const $=id=>document.getElementById(id); let lastStats=null;
  function show(name){views.forEach(v=>v.classList.toggle('active',v.id===name));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===name));title.textContent=titles[name]||name;history.replaceState(null,'','#'+name);if(name==='users')loadUsers();if(name==='subscriptions')loadSubscriptions();if(name==='ai')loadAI();}
  nav.forEach(n=>n.addEventListener('click',()=>show(n.dataset.view)));
  async function api(action,opts={}){const r=await fetch(`/api/admin?action=${action}`,{...opts,credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`API ${r.status}`);return d;}
  async function loadStats(){try{const d=await api('stats');lastStats=d;$('usersCount').textContent=d.total??'0';$('activeCount').textContent=d.active30d??'0';$('proCount').textContent=d.pro??'0';$('aiCount').textContent=d.aiRequests??'0';renderFinance(d);renderTrialSummary(d);}catch(e){$('usersCount').textContent='—';$('activeCount').textContent='—';$('proCount').textContent='—';$('aiCount').textContent='—';console.warn(e);}}
  function renderFinance(d){let box=document.getElementById('ownerFinance');if(!box){box=document.createElement('div');box.id='ownerFinance';box.className='panel';$('#overview')?.appendChild(box);}box.innerHTML=`<span class="eyebrow">OWNER FINANCE</span><h2>Деньги и экономика</h2><div class="cards" style="margin:0"><article class="card"><span>Оплачено всего</span><strong>$${money(d.actualRevenue)}</strong><small>реальные платежи</small></article><article class="card"><span>За этот месяц</span><strong>$${money(d.mtdRevenue)}</strong><small>paid PRO</small></article><article class="card"><span>Потенциальный MRR</span><strong>$${money(d.potentialMrr)}</strong><small>${d.pro} активных PRO × $4.99</small></article><article class="card"><span>Цена PRO</span><strong>$${money(d.price)}</strong><small>месячный тариф</small></article></div><p class="muted" style="margin-bottom:0">Фактическая выручка появится после подключения платёжного провайдера и записи платежей в payments. Потенциальный MRR — расчёт по активным PRO.</p>`;}
  function renderTrialSummary(d){const sub=$('#subscriptions'),panel=sub?.querySelector('.panel');if(!panel)return;panel.innerHTML=`<span class="eyebrow">BILLING & TRIAL</span><h2>Подписки и FREE 21 день</h2><div class="cards"><article class="card"><span>Активный PRO</span><strong>${d.pro}</strong><small>$4.99 / месяц</small></article><article class="card"><span>FREE trial</span><strong>${d.trial}</strong><small>21 день ещё действует</small></article><article class="card"><span>FREE завершён</span><strong>${d.expiredFree}</strong><small>нужен переход на PRO</small></article><article class="card"><span>Всего FREE</span><strong>${d.free}</strong><small>не PRO</small></article></div><div class="empty" style="min-height:100px"><b>Данные синхронизируются с Supabase.</b><span>При подключении оплаты здесь появится история реальных платежей.</span></div>`;}
  async function loadSubscriptions(){if(!lastStats)await loadStats();try{const d=await api('payments'),panel=$('#subscriptions .panel');if(!panel)return;let table=panel.querySelector('.payment-table');if(table)table.remove();if(!d.payments?.length)return;table=document.createElement('div');table.className='payment-table';table.style.cssText='overflow:auto;margin-top:18px';table.innerHTML=`<h3>Последние платежи</h3><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:10px">Дата</th><th style="padding:10px">Сумма</th><th style="padding:10px">План</th><th style="padding:10px">Провайдер</th><th style="padding:10px">Статус</th></tr></thead><tbody>${d.payments.map(p=>`<tr><td style="padding:10px;border-top:1px solid #242431">${fmt(p.paid_at)}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">$${money(p.amount_usd)}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${esc(p.plan||'PRO')}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${esc(p.provider||'—')}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${esc(p.status||'paid')}</td></tr>`).join('')}</tbody></table>`;panel.appendChild(table);}catch(e){console.warn(e);}}
  async function loadAI(){try{const d=await api('stats'),cards=$('#ai .cards');if(cards)cards.innerHTML=`<article class="card"><span>AI Coach + Scanner</span><strong>${d.aiRequests}</strong><small>запросов</small></article><article class="card"><span>PRO пользователи</span><strong>${d.pro}</strong><small>доступ к Scanner</small></article><article class="card"><span>AI стоимость</span><strong>—</strong><small>зависит от токенов OpenAI</small></article><article class="card"><span>Мониторинг</span><strong>LIVE</strong><small>Supabase usage log</small></article>`;}catch(e){console.warn(e);}}
  async function loadUsers(){const box=document.querySelector('#users .panel');if(!box)return;try{const d=await api(`users${$('userSearch')?.value?`&q=${encodeURIComponent($('userSearch').value)}`:''}`),rows=d.users||[];const old=box.querySelector('.user-table');if(old)old.remove();const empty=box.querySelector('.empty');if(empty)empty.remove();const wrap=document.createElement('div');wrap.className='user-table';wrap.style.cssText='overflow:auto;margin-top:18px';wrap.innerHTML=`<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:10px">Пользователь</th><th style="padding:10px">Тариф</th><th style="padding:10px">Регистрация</th><th style="padding:10px">FREE до</th><th style="padding:10px">PRO до</th><th style="padding:10px">Статус</th><th style="padding:10px"></th></tr></thead><tbody>${rows.map(u=>`<tr><td style="padding:10px;border-top:1px solid #242431"><b>${esc(u.username||u.name||'—')}</b><br><span style="color:#888895">${esc(u.email||'')}</span></td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${u.plan==='pro'?'👑 PRO':'FREE'}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${fmt(u.created_at)}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${u.plan==='pro'?'—':fmt(u.free_until)}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${fmt(u.pro_until)}</td><td style="padding:10px;border-top:1px solid #242431;text-align:center">${u.blocked?'🚫':'●'}</td><td style="padding:10px;border-top:1px solid #242431;text-align:right"><button class="btn user-action" data-id="${esc(u.id)}" data-op="${u.blocked?'unblock':'block'}">${u.blocked?'Разблокировать':'Заблокировать'}</button> <button class="btn user-action" data-id="${esc(u.id)}" data-op="${u.plan==='pro'?'free':'pro'}">${u.plan==='pro'?'Снять PRO':'Дать PRO 30д'}</button></td></tr>`).join('')}</tbody></table>`;box.appendChild(wrap);wrap.querySelectorAll('.user-action').forEach(b=>b.addEventListener('click',async()=>{try{const op=b.dataset.op;const body=op==='block'||op==='unblock'?{blocked:op==='block'}:op==='pro'?{plan:'pro',pro_until:new Date(Date.now()+30*86400000).toISOString()}:{plan:'free',pro_until:null,free_until:new Date(Date.now()+21*86400000).toISOString()};await api(`user&id=${encodeURIComponent(b.dataset.id)}`,{method:'PATCH',body:JSON.stringify(body)});await loadUsers();await loadStats();}catch(e){alert(e.message);}}));}catch(e){console.warn(e);}}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function fmt(v){return v?new Date(v).toLocaleDateString('ru-RU'):'—';} function money(v){return Number(v||0).toFixed(2);}
  async function health(){const apiEl=$('apiHealth'),coach=$('coachHealth');apiEl.textContent='● POST endpoint';apiEl.className='ok';coach.textContent='● готов к запросам';coach.className='ok';$('marketHealth').textContent='● клиентский feed';}
  $('refreshBtn')?.addEventListener('click',()=>{health();loadStats();});$('userSearch')?.addEventListener('input',()=>loadUsers());loadStats();health();show(location.hash.slice(1)||'overview');
})();
