import { sbJson } from './_supabase.js';
import { currentUser } from './auth.js';
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
async function requireAdmin(req,res){const user=await currentUser(req);if(!user)return json(res,401,{error:'Требуется вход в аккаунт.'});if(!user.is_admin)return json(res,403,{error:'Доступ запрещён.'});return user;}
function activePro(u,now){return u.plan==='pro'&&(!u.pro_until||Date.parse(u.pro_until)>now)&&!u.blocked;}
export default async function handler(req,res){try{const admin=await requireAdmin(req,res);if(!admin||admin.is_admin!==true)return;const action=String(req.query?.action||'stats');
 if(req.method==='GET'&&action==='users'){const q=String(req.query?.q||'').trim();const filter=q?`&or=(email.ilike.*${encodeURIComponent(q)}*,username.ilike.*${encodeURIComponent(q)}*,name.ilike.*${encodeURIComponent(q)}*)`:'';const users=await sbJson(`users?select=id,email,name,username,plan,pro_until,free_until,created_at,last_seen_at,blocked,is_admin&order=created_at.desc&limit=500${filter}`);return json(res,200,{users:Array.isArray(users)?users:[]});}
 if(req.method==='GET'&&action==='stats'){const [users,ai,payments]=await Promise.all([sbJson('users?select=id,plan,blocked,created_at,last_seen_at,pro_until,free_until&limit=10000'),sbJson('ai_usage?select=id&limit=10000').catch(()=>[]),sbJson('payments?select=id,amount_usd,status,paid_at&status=eq.paid&order=paid_at.desc&limit=10000').catch(()=>[])]);const list=Array.isArray(users)?users:[],paid=Array.isArray(payments)?payments:[],now=Date.now();const active30d=list.filter(u=>u.last_seen_at&&now-Date.parse(u.last_seen_at)<30*86400000&&!u.blocked).length;const pro=list.filter(u=>activePro(u,now)).length;const trial=list.filter(u=>!u.blocked&&u.plan!=='pro'&&u.free_until&&Date.parse(u.free_until)>now).length;const expiredFree=list.filter(u=>!u.blocked&&u.plan!=='pro'&&(!u.free_until||Date.parse(u.free_until)<=now)).length;const actualRevenue=paid.reduce((s,p)=>s+Number(p.amount_usd||0),0);const mtd=paid.filter(p=>Date.parse(p.paid_at)>=new Date(new Date().getFullYear(),new Date().getMonth(),1).getTime()).reduce((s,p)=>s+Number(p.amount_usd||0),0);const potentialMrr=pro*4.99;return json(res,200,{total:list.length,active30d,pro,free:list.length-pro,trial,expiredFree,aiRequests:Array.isArray(ai)?ai.length:0,actualRevenue,mtdRevenue:mtd,potentialMrr,price:4.99});}
 if(req.method==='GET'&&action==='payments'){const payments=await sbJson('payments?select=id,user_id,amount_usd,currency,plan,status,provider,external_id,paid_at,created_at&order=paid_at.desc&limit=500');return json(res,200,{payments:Array.isArray(payments)?payments:[]});}
 if(req.method==='PATCH'&&action==='user'){const id=String(req.query?.id||'');if(!id)return json(res,400,{error:'User id required'});if(id===admin.id)return json(res,400,{error:'Нельзя менять собственный статус владельца.'});const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{}),patch={};if(body.plan==='free'||body.plan==='pro')patch.plan=body.plan;if(body.pro_until===null||body.pro_until)patch.pro_until=body.pro_until;if(body.free_until===null||body.free_until)patch.free_until=body.free_until;if(typeof body.blocked==='boolean')patch.blocked=body.blocked;if(!Object.keys(patch).length)return json(res,400,{error:'Nothing to update'});await sbJson(`users?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(patch)});return json(res,200,{ok:true});}
 return json(res,405,{error:'Method not allowed'});
}catch(e){console.error('Admin API:',e);return json(res,500,{error:e.message||'Admin API failed'});}}
